services:
  xhsuhd:
    image: iptvtop/xhsuhd:latest
    container_name: xhsuhd
    restart: always
    ports:
      - "34567:34567"
    env_file:
      - ./config/xhsuhd.env

  home-iptv-proxy:
    image: ghcr.io/suyun888/home-iptv-proxy:latest
    container_name: home-iptv-proxy
    restart: always
    ports:
      - "28788:8787"
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      IPTV_CONFIG: /app/config/sources.yaml
      IPTV_IMAGE_NAME: ghcr.io/suyun888/home-iptv-proxy:latest
      IPTV_AUTO_UPDATE_ENABLED: "true"
      IPTV_UPDATE_COMMAND: docker compose -f /app/deploy/docker-compose.yml pull home-iptv-proxy && docker compose -f /app/deploy/docker-compose.yml up -d home-iptv-proxy
      IPTV_XHS_APPLY_COMMAND: docker compose up -d xhsuhd

  watchtower:
    image: containrrr/watchtower:latest
    container_name: home-iptv-proxy-watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_API_VERSION: "1.40"
    command: home-iptv-proxy --cleanup --interval 3600
